### PR TITLE
AC-7555 Add notification/alerts for testim test suite failures

### PR DESCRIPTION
**Pull request by philophilo**
### Changes introduced in: [AC-7555](https://masschallenge.atlassian.net/browse/AC-7555):
- installs jq on instances

### How to test
- Update stack settings to use this branch (AC-7555) for Chef (opsworks-web-python.git)
- On your stack's EC2 instance, run command `update custom cookbooks`, then run command `setup`
- Make a deployment to the stack with release `vTR-AC-7555v58` (Ensure that the necessary variables are given to the stack, the values are recorded in test4)
- A notification is sent to the #testim channel after deployment

#### merge first

expected variables
```
TESTIM_APP_DIRECTORY
TESTIM_TOKEN
TESTIM_PROJECT
TESTIM_TESTING_GRID
TESTIM_BUILD_CHANNEL
TESTIM_BUILD_CHANNEL_WEBHOOK
TESTIM_ECS_CLUSTER
TESTIM_ECS_FAMILY
TESTIM_IMAGE
TESTIM_SUBNET1
TESTIM_SUBNET2
TESTIM_SECURITY_GROUP
TESTIM_ASSIGNPUBLICIP
TESTIM_ECSTASKEXECUTIONROLE
TESTIM_LOGDRIVER
TESTIM_AWSLOGS_GROUP
TESTIM_AWSLOGS_REGION
TESTIM_AWSLOGS_STREAM_PREFIX
```

### CODE REVIEW

**Comment by pbx** [comment]
@philophilo - `testim/get_error_messages.py:56:80: E501 line too long (110 > 79 characters)`

**Comment by pbx** [comment]
Taking QA.

**Comment by pbx** [comment]
State of my review: I have created a [test stack](https://console.aws.amazon.com/opsworks/home?region=us-east-1#/stack/635dc471-56cf-4aa8-b504-d5db959fd922/stack) and had a a clarifying conversation with Philip. To do on Monday:
* Go to OpsWorks and, with AC-7555 as the chef cookbook branch, run **update custom cookbooks**,  then run **setup**
* Then set the needed stack vars, a la the PR diff and/or the stack settings on test4
* Then deploy **vTR-AC-7555v56** and wait for notification in #testim

**Review by shakirandagire — APPROVED** [review]
The code changes look good to me

**Review by pbx — CHANGES_REQUESTED** [review]
I followed the steps I posted on Friday, but the setup recipe did not succeed. From the [log](https://console.aws.amazon.com/opsworks/home?region=us-east-1#/stack/635dc471-56cf-4aa8-b504-d5db959fd922/instances/acd08429-90cf-4b3d-8b38-b82d93f1f8a1/log/e2cc5bf9-a87b-45b5-9d3f-5b55b05ef28b):
```
... 
NoMethodError
-------------
undefined method `property' for #<Class:0x007f1136e4cb88>
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/alternatives/resources/default.rb:1:in `class_from_file'
 
 
Relevant File Content:
----------------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/alternatives/resources/default.rb:
 
1>> property :link_name, String, name_property: true
2:  property :link, String, default: lazy { |n| "/usr/bin/#{n.link_name}" }
3:  property :path, String
4:  property :priority, [String, Integer], coerce: proc { |n| n.to_i }
5:  
6:  def define_resource_requirements
7:    requirements.assert(:install, :set, :remove) do |a|
8:      a.assertion do
9:        !new_resource.path.nil?
10:      end
 
 
 
[2020-05-11T13:17:20+00:00] ERROR: Running exception handlers
[2020-05-11T13:17:20+00:00] ERROR: Exception handlers complete
[2020-05-11T13:17:20+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage2/chef-stacktrace.out
[2020-05-11T13:17:20+00:00] ERROR: undefined method `property' for #<Class:0x007f1136e4cb88>
[2020-05-11T13:17:20+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Review by pbx — CHANGES_REQUESTED** [review]
The AC-7760 change seems good but now my deploy of `vTR-AC-7555v56` [fails](https://console.aws.amazon.com/opsworks/home?region=us-east-1#stack/635dc471-56cf-4aa8-b504-d5db959fd922/deployments/e04a3a77-72a4-42c3-9d36-5ba281b5c607) because it wants `TESTIM_ECS_SERVICE` (which is not in test4 settings).
```
Error: Referenced option does not exist: environment TESTIM_ECS_SERVICE---- End output of /srv/www/mc/current/bin/buildout -c deploy.cfg -vv ----Ran /srv/www/mc/current/bin/buildout -c deploy.cfg -vv returned 1[2020-05-12T15:53:03+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by pbx** [comment]
I added the "Don't merge" label because [this comment on the ticket](https://masschallenge.atlassian.net/browse/AC-7555?focusedCommentId=43177) notes a couple changes that must be made before merging.

**Review by pbx — APPROVED** [review]

**Review by pbx — CHANGES_REQUESTED** [review]
All my previous reviews' issues have been resolved. However, after a [successful deployment](https://console.aws.amazon.com/opsworks/home?region=us-east-1#/stack/635dc471-56cf-4aa8-b504-d5db959fd922/deployments/9cb39d28-85a1-4d8e-82ba-c44b7ab35dff) (of `vTR-AC-7555v58`) there is no notification in the [#testim channel](https://masschallengedev.slack.com/archives/CQF2K2LRH).

**Comment by philophilo** [comment]
@pbx let me checkout the error file...

**Comment by pbx** [comment]
Notification did appear (thanks for the heads up @philophilo!)

Remaining questions: https://github.com/masschallenge/accelerate/pull/2609#issuecomment-627521620

**Comment by pbx** [comment]
Latest QA attempt failed. See my [comment on the sibling PR](https://github.com/masschallenge/accelerate/pull/2609#pullrequestreview-413836042) for details.

**Review by pbx — APPROVED** [review]

**Comment by pbx** [comment]
OK, I deployed tag `vTR-AC-7555v63` it works!  Not merging yet, because 1) the sibling PR doesn't have two approvals, and 2) we need to get the required stack-setting variables in place on Staging.

**Comment by philophilo** [comment]
Resorting to installing `jq` as an os package under the mc-accelerate-layer

**Pull request closed without merging**
