### PR TITLE
[AC-9698] Timebox: Prevent/monitor front-end deploy failures

### PR DESCRIPTION
**Pull request by iankigen**
## [AC-9698](https://masschallenge.atlassian.net/browse/AC-9698)

**Changes introduced**
- add  buildout logs to stack deploy logs

**Testing**
- Use this branch as the custom Chef cookbooks revision
- Confirm that you can see buildout logs on the deploy logs

[Sibling PR](https://github.com/masschallenge/accelerate/pull/3398)

### CODE REVIEW

**Review by AmosWels — COMMENTED** [review]
This [link](https://us-east-1.console.aws.amazon.com/opsworks/home?region=us-east-1#/stack/885c6677-240a-425d-8244-6da3c48cd404/instances/5729bf70-f3a3-4866-9703-a3ffd132eb3c/log/05a96e29-1007-4d24-ac48-0acb901e7e48) points to the deploy log for the update_custom_cookbooks, I don't seem to find the buildout logs, at least on search for the added debug text `Buildout logs`

**Comment by iankigen** [comment]
From your latest deploy logs - Scroll to line 183 or search for `DEBUG: Buildout logs`
@AmosWels

**Comment by AmosWels** [comment]
> From your latest deploy logs - Scroll to line 183 or search for `DEBUG: Buildout logs` @AmosWels

oh, I see the log line

**Review by AmosWels — APPROVED** [review]
change looks good to me

**Review by kenware — APPROVED** [review]
Looks good

**Pull request merged**
